DB_PATH: C:\Users\Kyra\matchypatchy\matchypatchy.db
FRAME_DIR: C:\Users\Kyra\AppData\Local\Temp\MatchyPatchy_7z1b_9t2\Frames
LOG_PATH: C:\Users\Kyra\matchypatchy\matchpatchy.log
ML_DIR: C:/Users/Kyra/matchypatchy/Models
TEMP_DIR: C:\Users\Kyra\AppData\Local\Temp\MatchyPatchy_7z1b_9t2
