from matchypatchy import algo
from matchypatchy import config
from matchypatchy import database
from matchypatchy import gui
from matchypatchy import pairx

from matchypatchy.algo import (AnimlThread, BuildManifestThread,
                               CSVImportThread, DownloadMLThread,
                               FolderImportThread, LoadThumbnailThread,
                               MatchEmbeddingThread, QC_QueryContainer,
                               QueryContainer, ReIDThread, SequenceThread,
                               THUMBNAIL_NOTFOUND, animl_thread, download,
                               get_class_path, get_config_path, get_path,
                               import_thread, load, match_thread, models,
                               qc_query, query, reid_thread, sequence_thread,
                               thumbnail_thread, update_model_yml,)
from matchypatchy.config import (add, initiate, load, update,)
from matchypatchy.database import (COLUMNS, IMAGE_EXT, MatchyPatchyDB,
                                   VIDEO_EXT, fetch_media, fetch_regions,
                                   fetch_roi, fetch_roi_media, fetch_species,
                                   fetch_station_names_from_id, fetch_stations,
                                   fetch_surveys, get_bbox, get_sequence,
                                   individual_roi_dict, location, media,
                                   media_count, mpdb, sequence_roi_dict, setup,
                                   setup_database, species,)
from matchypatchy.gui import (AboutPopup, AlertPopup, ConfigPopup, DisplayBase,
                              DisplayCompare, DisplayMedia, DropdownPopup,
                              FAVORITE_STYLE, ImageWidget, ImportCSVPopup,
                              ImportFolderPopup, IndividualFillPopup,
                              IndividualPopup, LicensePopup, MATCH_STYLE,
                              MLDownloadPopup, MLOptionsPopup, MainWindow,
                              MediaEditPopup, MediaTable, READMEPopup,
                              ROIPopup, SpeciesFillPopup, SpeciesPopup,
                              StationFillPopup, StationPopup, SurveyFillPopup,
                              SurveyPopup, display_base, display_compare,
                              display_media, main_gui,
                              media_table, popup_alert, popup_config,
                              popup_dropdown, popup_import_csv,
                              popup_import_folder, popup_individual,
                              popup_media_edit, popup_ml, popup_readme,
                              popup_roi, popup_species, popup_station,
                              popup_survey, widget_image,)
from matchypatchy.pairx import (CMAPS, COLORS, XAIDataset, calculate_residuals,
                                choose_canonizer, core,
                                display_image_with_heatmap, draw_color_maps,
                                draw_matches, draw_matches_and_color_maps,
                                explain, get_feature_matches,
                                get_img_pair_from_paths,
                                get_intermediate_feature_maps_and_embedding,
                                get_intermediate_relevances,
                                get_pixel_relevance, get_pixel_relevances,
                                pairx, xai_dataset,)

__all__ = ['AboutPopup', 'AlertPopup', 'AnimlThread', 'BuildManifestThread',
           'CMAPS', 'COLORS', 'COLUMNS', 'CSVImportThread', 'ConfigPopup',
           'DisplayBase', 'DisplayCompare', 'DisplayMedia', 'DownloadMLThread',
           'DropdownPopup', 'FAVORITE_STYLE', 'FolderImportThread', 'HOME_DIR',
           'IMAGE_EXT', 'ImageWidget', 'ImportCSVPopup', 'ImportFolderPopup',
           'IndividualFillPopup', 'IndividualPopup', 'LicensePopup',
           'LoadThumbnailThread', 'MATCH_STYLE', 'MLDownloadPopup',
           'MLOptionsPopup', 'MainWindow', 'MatchEmbeddingThread',
           'MatchyPatchyDB', 'MediaEditPopup', 'MediaTable',
           'QC_QueryContainer', 'QueryContainer', 'READMEPopup', 'ROIPopup',
           'ReIDThread', 'SequenceThread', 'SpeciesFillPopup', 'SpeciesPopup',
           'StationFillPopup', 'StationPopup', 'SurveyFillPopup',
           'SurveyPopup', 'THUMBNAIL_NOTFOUND', 'VIDEO_EXT', 'XAIDataset',
           'add', 'algo', 'animl_thread', 'calculate_residuals',
           'choose_canonizer', 'config', 'core', 'database', 'display_base',
           'display_compare', 'display_image_with_heatmap', 'display_media',
           'download', 'draw_color_maps', 'draw_matches',
           'draw_matches_and_color_maps', 'explain', 'fetch_media',
           'fetch_regions', 'fetch_roi', 'fetch_roi_media', 'fetch_species',
           'fetch_station_names_from_id', 'fetch_stations', 'fetch_surveys',
           'get_bbox', 'get_class_path', 'get_config_path',
           'get_feature_matches', 'get_img_pair_from_paths',
           'get_intermediate_feature_maps_and_embedding',
           'get_intermediate_relevances', 'get_path', 'get_pixel_relevance',
           'get_pixel_relevances', 'get_sequence', 'gui', 'import_thread',
           'individual_roi_dict', 'initiate', 'load', 'location',
           'main_display', 'main_gui', 'match_thread', 'media', 'media_count',
           'media_table', 'models', 'mpdb', 'pairx', 'popup_alert',
           'popup_config', 'popup_dropdown', 'popup_import_csv',
           'popup_import_folder', 'popup_individual', 'popup_media_edit',
           'popup_ml', 'popup_readme', 'popup_roi', 'popup_species',
           'popup_station', 'popup_survey', 'qc_query', 'query', 'reid_thread',
           'sequence_roi_dict', 'sequence_thread', 'setup', 'setup_database',
           'species', 'thumbnail_thread', 'update', 'update_model_yml',
           'widget_image', 'xai_dataset']
