name: Tests

on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        cd matchypatchy_package
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov
      env:
        PIP_NO_BUILD_ISOLATION: 1
    
    - name: Run pytest
      run: |
        cd matchypatchy_package
        PYTHONPATH=src pytest tests/ -v --cov=src/matchypatchy/database --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.6.0
      with:
        files: ./matchypatchy_package/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true